### ISSUE TITLE
Is there a javascript close action?

### ISSUE THREAD

**Issue by onigetoc** [rudmanmrrod/material-dialog#3]
Is there a javascript close action?

I want to close the dialog on confirm.
Any javascript callback action to close the dialog?

**Comment by rudmanmrrod** [comment]
Technically there's no clean way to do that, but you can do in confirm callback something like this using jquery

```
MaterialDialog.dialog(
	"Text here",
	{
		title:"Dialog Title",
		modalType:"modal-fixed-footer",
		buttons:{
			close:{
				className:"red",
				text:"closed",
				callback:function(){
					alert("closed!");
				}
			},
			confirm:{
				className:"blue",
				text:"confirmed",
				modalClose:false,
				callback:function(modal){
					$('.material-dialog').last().modal("close")
				}
			}
		}
	}
);
```

**Comment by onigetoc** [comment]
thank's, i will try.

**Comment by onigetoc** [comment]
On the latest Materialize version, buton are not in the right order.
It will be interesting tu update. (i can make them float right to inverse them).
I would also add a css to create space between buttons like, `margine-left: 4px;`
Codepen test: https://codepen.io/onigetoc/pen/ErKeBX

**Comment by rudmanmrrod** [comment]
> On the latest Materialize version, buton are not in the right order.
> It will be interesting tu update. (i can make them float right to inverse them).
> I would also add a css to create space between buttons like, `margine-left: 4px;`
> Codepen test: https://codepen.io/onigetoc/pen/ErKeBX

Perfect, you can do pull request

**Comment by rudmanmrrod** [comment]
@onigetoc and in confirm you can simply remove modalClose property,

```MaterialDialog.dialog(
	"Text here",
	{
		title:"Dialog Title",
		modalType:"modal-fixed-footer",
		buttons:{
			close:{
				className:"red",
				text:"closed"
			},
			confirm:{
				className:"blue",
				text:"confirmed"
			}
		}
	}
);```
