### ISSUE TITLE
Line breaks?

### ISSUE THREAD

**Issue by teddyh-io** [rudmanmrrod/material-dialog#5]
I've entered a code like this
`
MaterialDialog.alert(
        "sentence one here.  \n line break to sentence two.",
        ...
`
but line break doesn't work. How would I get html and line breaks to work in that?

**Comment by rudmanmrrod** [comment]
Upps :sob: migrating from jquery i omitted that. I Will fix

**Comment by rudmanmrrod** [comment]
When i fix, a` <br>` tag can be enough. @jinsong04
